### ISSUE TITLE
levi - Vault deposit does not check for resulting zero shares

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#140]
levi

medium

# Vault deposit does not check for resulting zero shares

## Summary

Vault deposit does not check for resulting zero shares

## Vulnerability Detail

When a deposit is made to the vault, the function `_convertToShares` is called to convert the assets to shares:

```solidity
    function _convertToShares(EpochContext memory context, UFixed18 assets) private pure returns (UFixed18) {
        if (context.latestAssets.isZero()) return assets;
        return assets.muldiv(context.latestShares, context.latestAssets);
    }
```

There is the possibility of depositing a small amount of assets and zero shares getting minted due to the rounding down of shares. This would lead to a loss for the depositor.

## Impact

Loss of assets for the depositor

## Code Snippet

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L775-L778

## Tool used

Manual Review

## Recommendation

Add a check to revert if zero shares are returned.

**Comment by leviack3rman** [comment]
Escalate for 10 USDC

This should be a valid medium.
The issue has been acknowledged by the lead judge but chose not to set is as medium. This is inconsistent with past judging. Here is an example:

https://github.com/sherlock-audit/2022-12-notional-judging/issues/16

There is actual loss for the user.

Expecting the user to always check how many shares there are getting in advance is also flawed as those are two separate transactions meaning other transactions can happen in between when they check and when they deposit.

**Comment by KenzoAgada** [comment]
**Shares and assets are both on 1e18 accuracy** and minted 1:1.
This is unlike the issue that the escalator linked, where it is specifically mentioned that `the numerator precision (1e8) is much smaller than the denominator precision (1e18)`. Therefore that issue had a bigger impact.

The shares returned to the user are `assets.muldiv(context.latestShares, context.latestAssets)`.

Due to the same scale of the numerator/denominator, in our case the shares/assets would have to get out of sync and the user would have to deposit an unreasonably small amount to mint zero shares. (Again, unlike the linked issue where the scale is different.)

Due to the minimal impact I consider this a valid low, not enough for a medium.
But perhaps I should have notified the sponsor of this as a valid low, even if I believe the impact is as minimal as can be, if at all. @arjun-io FYI.

**Comment by jacksanford1** [comment]
@leviack3rman thoughts?

**Comment by leviack3rman** [comment]
I do agree that the user would have to deposit very small amounts for them to mint zero shares. The reason for submitting it as an issue is that the user should be protected from these scenarios however unlikely especially where a loss of funds is involved. If this is an acceptable scenario for the protocol then I am OK with the issue being invalid.

**Comment by jacksanford1** [comment]
Thanks for the response @leviack3rman. Probably good for the sponsor to see this one. Will mark as invalid though based on Kenzo's argument.

**Comment by jacksanford1** [comment]
Result:
Invalid
Unique
Invalid based on Kenzo's previous argument.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [leviack3rman](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/140/#issuecomment-1614203650): rejected
