### ISSUE TITLE
nobody2018 - ProductManager.syncAccount may cause new user to revert in some cases

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#143]
nobody2018

medium

# ProductManager.syncAccount may cause new user to revert in some cases

## Summary

A product coordinator can create an incentive program for his own product via `Incentivizer.create`. **One ProductManager per product**. The `programInfos` array in the `ProductManager` structure stores all static programs that have been created. **As time goes by, there are more and more incentive programs for the product, and this array will become larger and larger. Because useless incentive programs will not be deleted**. The `nextProgramFor` mapping in the `ProductManager` structure is used to record the next program to watch for for each user. The purpose of this is to prevent traversing the `programInfos` array every time `syncAccount` is called. However, when calling `syncAccount` for a new user, according to the current implementation, it is necessary to traverse the `programInfos` array. This may cause tx revert due to gas limit.

## Vulnerability Detail

Let's take a look at the code snippet of `ProductManager.syncAccount`:

```solidity
//ProductManager.sol    L107
function syncAccount(
        ProductManager storage self,
        IProduct product,
        address account,
        IOracleProvider.OracleVersion memory currentOracleVersion
    ) internal {

        // Add any unseen programs
->      uint256 fromProgramId = self.nextProgramFor[account];//when account is new user, fromProgramId = 0
        uint256 toProgramId = self.programInfos.length;
        for (uint256 programId = fromProgramId; programId < toProgramId; programId++) {//loop from 0 to toProgramId
->          self.activeProgramsFor[account].add(programId);
        }
        self.nextProgramFor[account] = toProgramId;

        // Settle programs
        uint256[] memory activeProgramIds = self.activeProgramsFor[account].values();//whole programInfos array
        for (uint256 i; i < activeProgramIds.length; i++) {//traverse the whole array
            uint256 programId = activeProgramIds[i];
            Program storage program = self.programs[programId];
->          program.settle(product, self.programInfos[programId], account, currentOracleVersion);//More gas is consumed here.
            if (!self.activePrograms.contains(programId) && currentOracleVersion.version >= program.versionComplete) {
                self.activeProgramsFor[account].remove(programId);
            }
        }
    }
```

The entire tx call process is as follows:

```flow
Product._settleAccount
  Incentivizer.syncAccount
    ProductManager.syncAccount	//assuming self.programInfos.length = 50
      1.  program.settle
      2.  program.settle
      ...
      50. program.settle
```

`Product._settleAccount` is a very important function, which is part of modifier `settleForAccount`. The modifier `settleForAccount` is used in `openTakeFor`/`closeTakeFor`/`openMakeFor`/`closeMakeFor`/`closeAll`.

Because useless incentive programs will not be deleted. As time goes by, there are more and more incentive programs for the product, and `programInfos` array will become larger and larger. Once a certain length is exceeded, DOS will occur due to the maximum gas limit of a block.

## Impact

- When the `programInfos.length` of `ProductManager` exceeds a certain value, this product can no longer have new users. Because  `openTakeFor`/`openMakeFor` from new user will revert.
- Some old users are also affected here. Old users come back after leaving for a long time. If the difference between the value in `nextProgramFor` and `programInfos.length` exceeds a certain value, the same problem will actually occur.

## Code Snippet

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/incentivizer/types/ProductManager.sol#L107-L132

## Tool used

Manual Review

## Recommendation

Check if `account` is a new user in `ProductManager.syncAccount`, if yes, add all programIds in `self.activePrograms`. Then assign `self.nextProgramFor[account]` to `self.programInfos.length`.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is valid M. The reason it was rejected by the leader judge is: the program array is controlled by the product owner.

**This is a problem that may occur in the long run**. Although there is such a [check](https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/incentivizer/Incentivizer.sol#L52) in the `Incentivizer.create` function, it only checks the number of currently active programs. **The longer a product runs, the more programs it has**. It is reasonable for the owner of the product to continuously launch new programs in order to have/keep more users. 
In terms of annual time cycle, it is constantly happening that old programs expire and new programs are created. Because the `programInfos` array will not be deleted, only increased. Then the problems described in this report arise. Please review.

**Comment by KenzoAgada** [comment]
The escalator writes that "The product owner does not control the programInfos array". **But only the product owner can add new programs.** If he does not control it, who does?
The judging guidelines [specifically state](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-considered-valid) about out of gas issues:
> **In case the array length is controlled by the trusted admin/owner** or the issue describes an impractical usage of parameters to reach OOG state then these submissions **would be considered as low.**

I understand that the watson is pointing out to the fact that all programs (even old) will be in `programInfos` and can not be removed from there. But as only the owner can add programs, by the judging guidelines I don't think this can be considered more than a valid low.

**Comment by securitygrid** [comment]
Indeed, only the product owner can add new programs. As I mentioned above, the constant creation of incentive programs is a requirement for product owner. This is not a malicious act. The owner does not know that programInfos cannot exceed a certain number. From the perspective of `complete` code implementation, the development team considers that programInfos will be too large, so they use mapping to record, right?

**Comment by KenzoAgada** [comment]
- I do not really understand what you meant in the last sentence. Maybe you did not mean `complete`?
- Sorry, but your points and questions do not change the basic fact that I mentioned above, nor have you acknowledged it, that Sherlock judging guidelines **specifically** mention that OOG issues when the admin controls the array length would be considered low.
- This issue was actually reported in the Veridise audit that was linked in the readme, issue PER010 page 25, and already acknowledged by the sponsor.

Due to the above reasons I still think that the issue is invalid.

**Comment by securitygrid** [comment]
agree with your 3th resason(issue PER010 page 25). It's a known issue.
invalid.
This is a consequence of my not reading previous reports. 
Thanks. @KenzoAgada

**Comment by KenzoAgada** [comment]
🙏
