### ISSUE TITLE
Bauchibred - Product's Flywheel Dependency on Oracle Updates is a Downside

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#17]
Bauchibred

medium

# Product's Flywheel Dependency on Oracle Updates is a Downside

## Summary

The product's flywheel in protocol is dependent on continuous updates from an oracle. However, if the oracle stops updating, it can lead to a stagnant state where the flywheel stops spinning. This creates a significant downside as the protocol and vault become extensively stuck.
It is important to note that oracles can go offline for various reasons, such as maintenance or token prices falling to zero. In such cases, the flywheel won't spin, resulting in halted operations due to the unavailability of updated data.

## Vulnerability Detail

Currently, only one oracle source is integrated into the protocol (chainlink), exacerbating the issue.

Chainlink, a popular oracle provider, has taken oracles offline in extreme cases to ensure the accuracy and reliability of data. For instance, during the UST collapse, Chainlink temporarily paused the UST/ETH price oracle to prevent the dissemination of inaccurate data to protocols.

## Impact

The dependency on the oracle updates for the product's flywheel poses a significant risk. If an oracle goes down or stops updating, the flywheel will cease to function, leaving the protocol and vault(extensively) in a stucked state. This can have far-reaching consequences, including the inability to execute crucial operations and potential financial losses for users.

## Code Snippet

[BalancedVault.sol](https://github.com/sherlock-audit/2023-05-perennial/blob/0f73469508a4cd3d90b382eac2112f012a5a9852/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L2-L858)

## Tool used

Manual Review

## Recommendation

Introduce Safeguards: Implement a safeguard mechanism to protect against potential issues arising from oracle downtimes or failures. This can involve integrating fallback or backup oracles that can be activated in case the primary oracle becomes unresponsive. This redundancy will help ensure the availability of updated data and enable the flywheel to continue spinning.

Apologies for the confusion. Here is the merged report focusing on one issue:

---

**Comment by Bauchibred** [comment]
Escalate for 10 USDC

Firstly I would like to appreciate the judge for the [spreadsheet](https://docs.google.com/spreadsheets/d/1kAsg8XAreeN0IlxRLqb7588EgycyHm33lzapokIcRhk/edit#gid=0) you provided on submitted issues, really helped to know what's wrong and not to make unnecessary escalations, but I would like you to re check this issue and also forward to sponsors for a review.

This issue was submitted after an extensive discussion with the sponsors, discussion attached below:

## **Discussion with qlo about this finding**

### **Context:**

Flywheel dependence on oracles

**Query:**

> Can you kindly clarify how a versiion from an oracle is created, cause at present implemntation If an oracle goes down (This can happen in a number of scenariios, take the UST/Luna event for example) currentepoch can never be completed, isn't this a big issue since protocol would have to be stucked in the same epoch or how do you plan on sorting out an issue like this?

```solidity
    /**
     * @notice Returns the whether the current epoch is currently complete
     * @dev An epoch is "complete" when all of the underlying oracles have advanced a version
     * @return Whether the current epoch is complete
     */
    //  @audit But having all underlying oracles advancing their versions as a requirement  before an epoch is completed, easily costs the protocol to be stucked in an epoch
    function currentEpochComplete() public view returns (bool) {
        for (uint256 marketId; marketId < totalMarkets; marketId++) {
            if (
                Math.min(markets(marketId).long.latestVersion(), markets(marketId).short.latestVersion()) ==
                _versionAtEpoch(marketId, _latestEpoch)
            ) return false;
        }
        return true;
    }
```

**Reply:**

> Yes that's correct, if the oracle stops updating the product flywheels won't spin


**Follow-up Query:**

re 3 Isn't this bad for the protocol, if the product flywheels won't spin, doesn't that mean that all pending deposit / redemption wouldn't be processed since epoch can never settle, potentially meaning that all pending redeems are stucked in the contract and the contract can't function normally since even pending deposits wouldn't get processed?

**Reply:**

> yes, this is true for the core protocol and for the vaults by extension.

I beleive you assume finding is _vague_ is the fact that a particular window was not stated, but as clearly seen in codebase and as clearly acceped by sponsors (*qlo* in this case) this is an issue that leads to different variety of issues and as at the time of writing this report I believe that the root cause of the issue is the dependency on an oracle to spin, also about answering your question of how many oracles are adequate, there is no "right" answer to say, but implementing even just one fallback oracle massively reduces the chances of this happening. 

Finally I didn't put in more details/time in writing report compared to other submitted issues as I assumed that I had confirmed the issue with sponsors and there shouldn't be any need to convince them in the report again, which I now understand is not the right way to go since the issues submitted in a contest are first reviewed by the judge and then the sponsors, so would put in more effort next time.

**Comment by Evert0x** [comment]
> 
> 
> Escalate for 10 USDC
> 
> Firstly I would like to appreciate the judge for the [spreadsheet](https://docs.google.com/spreadsheets/d/1kAsg8XAreeN0IlxRLqb7588EgycyHm33lzapokIcRhk/edit#gid=0) you provided on submitted issues, really helped to know what's wrong and not to make unnecessary escalations, but I would like you to re check this issue and also forward to sponsors for a review.
> 
> This issue was submitted after an extensive discussion with the sponsors, discussion attached below:
> 
> ## **Discussion with qlo about this finding**
> 
> ### **Context:**
> 
> Flywheel dependence on oracles
> 
> **Query:**
> 
> > Can you kindly clarify how a versiion from an oracle is created, cause at present implemntation If an oracle goes down (This can happen in a number of scenariios, take the UST/Luna event for example) currentepoch can never be completed, isn't this a big issue since protocol would have to be stucked in the same epoch or how do you plan on sorting out an issue like this?
> 
> ```solidity
>     /**
>      * @notice Returns the whether the current epoch is currently complete
>      * @dev An epoch is "complete" when all of the underlying oracles have advanced a version
>      * @return Whether the current epoch is complete
>      */
>     //  @audit But having all underlying oracles advancing their versions as a requirement  before an epoch is completed, easily costs the protocol to be stucked in an epoch
>     function currentEpochComplete() public view returns (bool) {
>         for (uint256 marketId; marketId < totalMarkets; marketId++) {
>             if (
>                 Math.min(markets(marketId).long.latestVersion(), markets(marketId).short.latestVersion()) ==
>                 _versionAtEpoch(marketId, _latestEpoch)
>             ) return false;
>         }
>         return true;
>     }
> ```
> 
> **Reply:**
> 
> > Yes that's correct, if the oracle stops updating the product flywheels won't spin
> 
> 
> **Follow-up Query:**
> 
> re 3 Isn't this bad for the protocol, if the product flywheels won't spin, doesn't that mean that all pending deposit / redemption wouldn't be processed since epoch can never settle, potentially meaning that all pending redeems are stucked in the contract and the contract can't function normally since even pending deposits wouldn't get processed?
> 
> **Reply:**
> 
> > yes, this is true for the core protocol and for the vaults by extension.
> 
> I beleive you assume finding is _vague_ is the fact that a particular window was not stated, but as clearly seen in codebase and as clearly acceped by sponsors (*qlo* in this case) this is an issue that leads to different variety of issues and as at the time of writing this report I believe that the root cause of the issue is the dependency on an oracle to spin, also about answering your question of how many oracles are adequate, there is no "right" answer to say, but implementing even just one fallback oracle massively reduces the chances of this happening. 
> 
> Finally I didn't put in more details/time in writing report compared to other submitted issues as I assumed that I had confirmed the issue with sponsors and there shouldn't be any need to convince them in the report again, which I now understand is not the right way to go since the issues submitted in a contest are first reviewed by the judge and then the sponsors, so would put in more effort next time. 
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KenzoAgada** [comment]
Hi @Bauchibred . First of all thanks for the kind words.

@arjun-io , can you please read the issue and escalation and share your perspective on it?

Personally, even when reading the escalation, while evidently the sponsor agrees that there is reliance on the one oracle source and it's jamming would jam the flywheel, I'm not sure it means that the issue is valid as a medium (or that the sponsor thinks so). It kind of feels like a general stating the obvious to me. If we're thinking of audit value to the sponsor, I think it's unlikely that they were unaware of this issue.

However I agree that there may be a point raising such an issue in an audit, especially if Sherlock insures the protocol.

Let's hear the sponsor and Sherlock's view on the matter.

**Comment by arjun-io** [comment]
Agreed with @KenzoAgada here - this is a core decision on how the protocol works. Do note that if the underlying oracle were to stop updating there are ways (through updating the oracle) to alleviate this case. However, in general the products depending on oracle updates is the way the protocol is designed.

**Comment by jacksanford1** [comment]
Would like to hear more about what happens if the flywheel stops spinning and what kind of impact that could have @Bauchibred 

And question for @arjun-io: if the flywheel stops, what exactly happens? I could see this issue falling into the same category as the "MEV will liquidate users before they can salvage their positions"?

**Comment by arjun-io** [comment]
If the flywheel stops, then position changes can't transition from `pre` to settled. This means that effectively _all_ actions for that market paused until the flywheel starts again. Agreed that if the price deviates greatly from when the flywheel was last spinning, it could result in users being immediately liquidated were the flywheel to turn on again.

**Comment by Bauchibred** [comment]
@jacksanford1 I believe the _flywheel's dependency_ leads to different issues and shouldn't be coined to just one since _all actions would be paused_, siding with your view to explain one case of how this easily attracts MEVs for whenever it comes back on, using this comment from  sponsor:
>Agreed that if the price deviates greatly from when the flywheel was last spinning, it could result in users being immediately liquidated were the flywheel to turn on again.

Now note that while users get liquidatable when the flywheels aren't spinning, even if they have the funds and would like to deposit, they can't do that, and if the wheel were to come back on and users try to deposit at this time, liquidators could easily front run them, this part could be somewhat related to the argument in #190, since the flywheels being off is essentially an _unintentional pause_, key to keep in mind that exacerbating the issue Is the fact that this pause is unintentional.

More complex attack cases could still be gotten from this issue, where another  potential window I believe  could be related to users trying to redeem and do away with their assets since they believe that if they keep on holding these assets, they might make great losses ( _in $ value_), now they try redeeming but this gets delayed  for as long as the products/vaults are in a stuck state, and if users analysis was correct, when the flywheel turns back on they might have realised great losses  _in $ value_.

TLDR: This impacts each and every one of `all the actions` that get `unintentionally paused` when the flywheel stops spinning.

**Comment by jacksanford1** [comment]
Hmm ok, @KenzoAgada how do you think these types of issues should be handled? Like this and #190? Is it a valid issue to just say that a pause in the functioning of the oracle could result in bad things happening? On one hand, if there were an easy way to prevent this, you could say this is a valid issue because not fixing it would be bad. On the other hand, if it's completely core to how users expect the protocol to work, then you could say it's invalid.

**Comment by arjun-io** [comment]
As per the recommendation - Perennial _does_ have the ability to change the oracle of a product via the updateOracle function in the case that a specific oracle is fully bricked.

**Comment by jacksanford1** [comment]
Thanks Arjun. That would point even more in the direction of making this invalid I think.

@Bauchibred I think this is a legitimate Low issue, but it doesn't reach Medium severity because there isn't a very likely situation where Perennial won't be able to act within hours to remedy the situation (change the oracle, etc.) and the impact on users from a few hours of downtime is unlikely to be large (sure maybe a few users get liquidated, but that's not a large enough magnitude of loss imo to warrant a Medium).

**Comment by Bauchibred** [comment]
@jacksanford1  That's a valid stance and I'm convinced that in as much as Perennial can act in a timely manner to update the oracle then the harm caused by this can be largely minimized, the root of my argument was to implement an automatic fallback mechanism to mitigate this case instead of say updating the oracle manually, since the oracle is going to be changed anyways. Also about the amount of loss, one can say it all depends on how long this goes on for, and the amount the users who could get liquidated have at stake, we can't fix an exact number on that. 

Fair enough case is subjective and any decision asides being invalid is fair imo.

**Comment by jacksanford1** [comment]
Appreciate the message @Bauchibred. Can't speak to whether Perennial will decide to add a fallback oracle, but I definitely agree that there's a lot of room for uncertainty in this issue when it comes to how many users will be affected, amount of funds lost and how long the condition will last. But based on the fairly ringfenced timespan that one could reasonably expect, I think this issue should be Low.

**Comment by jacksanford1** [comment]
Result:
Invalid
Unique
Reason in previous message.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Bauchibred](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/17/#issuecomment-1613604722): rejected
