### ISSUE TITLE
mstpr-brainbot - Vaults can't handle the incentives distributed by the products

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#43]
mstpr-brainbot

high

# Vaults can't handle the incentives distributed by the products

## Summary
Vaults are eligible for product incentive rewards but lack the necessary functions to claim and distribute these rewards to users within the vault. 
## Vulnerability Detail
In the current scenario, if a product has an incentiviser, all depositors are eligible for these incentives. As vaults also make deposits into products, they are also qualified to claim rewards from the incentiviser. However, the vaults lack the functionality to claim these rewards from the incentiviser, and there isn't any existing code to distribute these rewards to the users within the vault. Even when a vault does not participate in the incentives, its presence still dilutes the share of rewards for other product users in the reward pool.
## Impact
Although the rewards can be claimed for anyone, vault has no functionality to handle the reward tokens. This will create an economical damage to reward depositor (program owner) and the users in the product hence, I'll call it as high.
## Code Snippet
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/Product.sol#L167
## Tool used

Manual Review

## Recommendation
Implement functionality allowing vault depositors to claim product-related rewards if they're eligible. If vaults are excluded from such rewards, their deposited balance should not factor into the incentiviser's distribution calculations, thereby increasing other product depositors' reward shares.

**Comment by roguereddwarf** [comment]
Escalate for 10 USDC

According to the sponsor's comment this is intended behavior.

The Vault is a separate domain that is not part of the core protocol and upon deployment of a Vault there must be an agreement with the market operator that there won't be any issue with the incentives.

Also, upon talking to the sponsor, I have been told that there is a strong trust relationship between the Vault deployment and the Market operators, such that the fact that the Vault currently does not handle incentives is not an issue.

Furthermore, the fact that Market operators / Vault operators can sabotage the protocol is out of scope.

**Comment by mstpr** [comment]
Escalate for 10 USDC

I disagree with the escalation made above and also the sponsor's comment. Although the vault should be ok by not taking part on incentives distributed in the products, vault is still entitled to them which means that vault will dilute the incentive APR for the other users. In current design, the incentive depositor basically depositing rewards and they know that some of them will never be claimable so basically some of the incentive tokens are stuck in the incentiviser because vault can't claim and handle them. Considering vaults are holding considerable amount of positions in products, most of the incentives will be lost for the users. Furthermore, the incentivizer is not encouraged to initiate an incentive program since most of the incentives will be trapped in because of vaults inability to handle them. Also, since the vault implementation is handled by the Perennial, the next implementation that will handle the vaults incentives is unknown, such that the incentivizer has no idea how will the vault handle the incentives that's been claimable for the vault for the due time.

I don't think there is "sabotage" issue here too, this is just how it would work with the current scope of code. 

Sponsor team should've stated in docs that the incentives will start for products when the vault has a different implementation where it can handle the incentives or simply stating that this issue is invalid/out of scope.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is valid.
In the readme or code comments, there is no mention that the vault does not claim incentive tokens is intentional. As the maker of the product, vault is also the user. The first escalation mentions Watson's communication with the sponsor, which does not comply with Sherlock's rules.

**Comment by KenzoAgada** [comment]
I think this is quite obviously a valid high issue.

mstpr and securitygrid above me already laid out the reasons.

**Comment by SergeKireev** [comment]
Did not escalate because I agreed with @roguereddwarf 's escalation.

First of all as stated by the sponsor this is intended behavior, and is more akin to a missing feature than a bug.

Indeed claiming functionality is missing but no funds are lost by any means, rewards of the incentivizer still rightfully are attributed to the vault. The vault is an upgradeable proxy which can implement claiming and distribution of rewards when needed:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/deploy/01_deploy_vault_alpha.ts#L26-L42

This is of medium severity at most

**Comment by securitygrid** [comment]
Upgrading the contract can fix all issues. This way is out of scope. In this contest, it is a fact that the rewards are stuck in the contract.

**Comment by arjun-io** [comment]
From our perspective - this was a design decision when building the vaults, knowing that if protocol owned products ever did decide to turn on incentives we would need to come up with a way to handle those in the vaults. However, the added complexity at the time was not worth the effort. Since the vaults are explicitly not part of the core protocol, this is akin to another builder building a vault product on top of Perennial and not supporting incentives rather than an issue within the protocol itself.

We'll leave this up to judging, but from our view this is "intended behavior" that is not a bug but instead a missing feature and we've stated the same when previous auditors had looked at this code and asked.  Additionally FWIW, temporarily freezing funds is generally classified as Medium (as per Sherlock's Immunefi bug bounty guidelines)

**Comment by jacksanford1** [comment]
Whether or not it was clear that this functionality was intended to be missing, the severity of the issue doesn't seem nearly large enough to warrant a Medium or High, and the fix seems quite easy. It looks like it is virtually impossible for a program owner or user to lose a material amount of funds due to this bug. 

(Btw Immunefi's classification guidelines are not directly transferrable to Sherlock contests -- Sherlock contests don't have a Critical severity while Immunefi does).

**Comment by KenzoAgada** [comment]
If we're talking of severity -
It seems that at the moment the user _is_ losing funds, no? The incentivizer programs funds, which he is entitled to, and can assume he's getting.
We can say that one day Perennial might scrape the whole event and program history and update the vault and create a way for users to redeem their rewards, but it's hypothetical...

**Comment by arjun-io** [comment]
"entitled" is a strong word here, as the users are explicitly _not_ opting to LP in a way that would entitle them to rewards directly from the protocol mechanism. The vault could very well keep the incentivized funds as a sort of fee for usage, no? If we're talking in hypotheticals here.

**Comment by KenzoAgada** [comment]
Hmm... Yes, the vault could do so.
But I don't think that "the users are **_explicitly_** not opting to LP in a way that would entitle them to rewards"... Because there is no indication that the vault acts differently.
I understand that you look at vaults as not part of the core protocol, and therefore missing features are ok, but I'm not sure that distinction is apparent to users. [Reading the docs](https://docs.perennial.finance/lps-makers/vaults), nothing distinguishes the vaults from the rest of the protocol. They are also a part of the [official app](https://app.perennial.finance/earn). So why would a user expect different behavior?
I agree "entitled" might be too strong a word here.
But I think it is reasonable for users (and auditors) to expect same behavior with regards to rewards.

**Comment by arjun-io** [comment]
The docs only very briefly mention incentivization, and that's in a developer focused section which gives no indication on how it works at a user level. So if reading the code is applicable in one case it should be applicable in the other.

**Comment by KenzoAgada** [comment]
Yes, it's a fair point that the docs do not really mention the incentivization to the users.
(I still think that the rest of the abovementioned points are legitimate for consideration of the validity of the issue.)

**Comment by securitygrid** [comment]
If there is only one user participating in the vault, then the function of the vault without a claim only affects one user. If the Vault has N users, the reward is shared by N users. This is not a simple function. The claim is only the first step, and the rewards need to be distributed to the participating users, right?

**Comment by jacksanford1** [comment]
Based on @arjun-io's last comment:

> edit: I'm realizing the docs do say "work the same as any maker position" - I concede that this might make people who know about incentivization assume vaults might distribute them as well. I'll leave this to the admins to decide.

I think it's worth rewarding this as a Medium. No giant exploit would occur due to this, but maybe some depositors will get upset enough about the lost rewards that they'll come after Perennial or Sherlock for them. So this issue is probably good enough to flag as a Medium.

I guess the last question which could bump it down to Low/Informational would be "How recoverable are the rewards? Are they lost forever or need a simple upgrade/manual distro from Perennial to get to the right users?"

**Comment by arjun-io** [comment]
> I guess the last question which could bump it down to Low/Informational would be "How recoverable are the rewards? Are they lost forever or need a simple upgrade/manual distro from Perennial to get to the right users?"

It depends - in this scenario where incentives rewards were distributed _before_ the vaults supported them, it would most likely entail an "airdrop" style claim where off-chain distributions are calculated based on historical deposits and the vaults would be upgraded to `claim` and `transfer` the portion rewards to the airdrop contract to allow those users to claim.

**Comment by jacksanford1** [comment]
If that's the case, then there is really no loss of funds, just an inconvenience for good actors distributing funds properly to those who deserve them. Would consider it a Low in that case. @mstpr

**Comment by securitygrid** [comment]
According to rules:
Loss of airdrops or liquidity fees or any other rewards that are not part of the original protocol design is not considered a valid high/medium.

The incentive contract is part of the protocol design. The accumulation of rewards is in the core process.

**Comment by jacksanford1** [comment]
@securitygrid I think I agree with your statement from the docs. However, just because the functionality is part of the protocol design doesn't not automatically mean any issue related to it is a valid High/Medium. 

In this case your point from above:
> basically some of the incentive tokens are stuck in the incentiviser because vault can't claim and handle them

Would constitute a Medium/High if the funds were stuck there forever/unrecoverable. However it seems that an upgrade is able to save the funds that get stuck in the incentivizer, so there is no loss of funds potential with this issue. Therefore it cannot be a High/Medium and must be a Low.

**Comment by jacksanford1** [comment]
Result:
Low
Has duplicates 
This one was very tough and I think there are many valid arguments for making it Medium. However, at the end of the day the likelihood of funds being lost due to this bug seems to be close to zero, and the funds at risk are only the incentives (not principal) so going with Low here. Appreciate everyone's comments above and the lively discussion.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [roguereddwarf](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/43/#issuecomment-1615087191): accepted
- [mstpr](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/43/#issuecomment-1615186597): rejected
- [securitygrid](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/43/#issuecomment-1615365614): rejected
