### ISSUE TITLE
roguereddwarf - BalancedVault.sol: V2 upgrade does not implement V1 functions which means users can lose access to their funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#56]
roguereddwarf

high

# BalancedVault.sol: V2 upgrade does not implement V1 functions which means users can lose access to their funds

## Summary
The current `BalancedVault` is meant as an upgrade for the current single market implementation of the `BalancedVault`.

We can see this in the initializer (initializing version 2):
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L113

The issue is that shares in the V1 Vault are transferrable
https://github.com/equilibria-xyz/perennial-mono/blob/5ba9c9fc594cc476e9370bd68eb5ac7fd04bfc10/packages/perennial-vaults/contracts/BalancedVault.sol#L215-L233

```solidity
    function transfer(address to, UFixed18 amount) external returns (bool) {
        _settle(msg.sender);
        _transfer(msg.sender, to, amount);
        return true;
    }

    /**
     * @notice Moves `amount` shares from `from to `to`
     * @param from Address to send shares from
     * @param to Address to send shares to
     * @param amount Amount of shares to send
     * @return bool true if the transfer was successful, otherwise reverts
     */
    function transferFrom(address from, address to, UFixed18 amount) external returns (bool) {
        _settle(from);
        _consumeAllowance(from, msg.sender, amount);
        _transfer(from, to, amount);
        return true;
    }
```

However in the V2 implementation the `transfer` and `transferFrom` functions have been removed.

## Vulnerability Detail
The vulnerability can occur because based on V1 the `shares` might be managed by a contract that does not itself have the ability to redeem them.

However with the upgrade to V2, the assets corresponding to the shares get lost because the contract would not be able to transfer the shares somewhere else where they can be redeemed.

## Impact
Loss of funds because shares could not get redeemed.

Note that this scenario does not rely on a user error.
The shares might be owned by a smart contract and be subject to the logic of the contract. Thereby it's not possible that the smart contract just transfers them somewhere where they can be redeemed before the V2 upgrade.

## Code Snippet
V2 `BalancedVault`:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L30

V1 `BalancedVault`:
https://github.com/equilibria-xyz/perennial-mono/blob/master/packages/perennial-vaults/contracts/BalancedVault.sol

## Tool used
Manual Review

## Recommendation
Implement the `transfer` and `transferFrom` functions in the V2 `BalancedVault` such as to not break compatibility.

**Comment by mstpr** [comment]
Escalate for 10 USDC

I think this is a valid low/informational issue. 

As the sponsor states, "We verified that no contracts currently hold tokens, and we'll verify that again before deploying this upgrade" and also it makes sense to inform depositors that there will be no transfers such that they can unwind their position from their contracts. 

Also, the approve method is still there, which as long as the contract has approval method some other account/contract can redeem behalf of the token holder.

**Comment by KenzoAgada** [comment]
Responding to the escalator's 2 points:
> As the sponsor states, "We verified that no contracts currently hold tokens, and we'll verify that again before deploying this upgrade" and also it makes sense to inform depositors that there will be no transfers such that they can unwind their position from their contracts.
- During the contest there was no indication that the sponsor was aware of this problem. It might have been an oversight which would caused stuck funds upon upgrade.
> Also, the approve method is still there, which as long as the contract has approval method some other account/contract can redeem behalf of the token holder.
- the approve method is there, but there is no `transferFrom` method to actually transfer the funds.

So both escalation points seem invalid to me.

I honestly do think this is quite an edge case and wondered whether it should be accepted. In the end I think it's a good observation that was worthy of being submitted and could have impacted user funds, so a medium is appropriate.

**Comment by jacksanford1** [comment]
Agree that because it was unclear that the sponsor was aware of this during the contest, it cannot be invalidated because of the "intentionality" of removing those functions by the sponsor and manually checking addresses. @mstpr

**Comment by mstpr** [comment]
I believe this should be considered same as #43 

The main counter argument for #43 was that the protocol team can implement a newer version of the vault where it can handle the incentives. Same applies here, if protocol team notices some users transferred their shares they can implement a newer version where it can handle it. It is definitely a design choice. This is definitely an informational issue because there is no loss of funds since protocol team can handle another implementation. 

Also, the previous Perennial contracts were not in scope, if we need to check the all functionalities and their logic of previous implementation of the code than protocol team should state that these contracts are also in scope so that every Watson can check the prev implementation in deep too. 

Also, "Agree that because it was unclear that the sponsor was aware of this during the contest" is a wrong statement. As the sponsor says, "We intentionally removed this functionality. We verified that no contracts currently hold tokens" so they knew before they develop the current implementation and that's why they excluded these functions. It's clear that the protocol team knew about this and they took necessary actions. That's why this is a design choice. Not every function need to be implemented in the new implementation, that's the whole point of upgradable contracts. 

@jacksanford1

**Comment by jacksanford1** [comment]
I have some thoughts but I'll let @roguereddwarf @KenzoAgada provide their input first

**Comment by KenzoAgada** [comment]
I agree that there can be judging similarity between this and #43, as both issues can be downgraded due to contract upgradeability.

I don't really like "contract is upgradeable" as a reason for downgrading honestly. I feel like auditors are auditing and finding bugs exploits and oversights in the current codebase, and then some can be brushed aside by saying "we can fix via update", while the auditor did the work to discover if any issues are there, and perhaps even notified the protocol of them.

However, I have to admit that **in practice** the upgradeability does lower the severity, and Sherlock tries to accept issues only with severe consequences.

I thought that this issue raises a valid concern and should be accepted. But the consequences were already hypothetical to begin with, and with the upgradeability, it's unlikely that it would have caused any big serious harm (if at all).

So while (sorry, again) I'm personally not a fan of using upgradeability to lower severity, and I see a case for this issue and #43 to both be considered medium,
to maintain Sherlock judging guidelines and consistency I think this and #43 can be considered low.

**Comment by jacksanford1** [comment]
@KenzoAgada @roguereddwarf I agree that using upgradability to downgrade an issue is an unfortunate "cop out" in a lot of situations and doesn't always reward auditors commensurately for the novelty of the issue found. 

However, Sherlock is committed to being grounded in reality and if there's a way to easily upgrade out of a problem, then this 100% lowers the potential severity of the issue. Of course, upgradability can have lots of issues associated with it in reality, and those should be factored in too when relevant. 

The practical damage that can be caused by this issue seems very low, so the severity should be Low in my opinion.

**Comment by jacksanford1** [comment]
Result:
Low
Unique
See previous comment for reasoning.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/56/#issuecomment-1613160405): accepted
