### ISSUE TITLE
roguereddwarf - BalancedVault.sol: Rebalancing logic can get stuck, leading to a loss of funds if a user wants to resolve it

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#66]
roguereddwarf

medium

# BalancedVault.sol: Rebalancing logic can get stuck, leading to a loss of funds if a user wants to resolve it

## Summary
Each action that is executed in the Vault (`deposit`, `redeem`, `claim`, `sync`) calls the `_rebalance` function. This function first rebalances the collateral and then the position:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L431-L434

First collateral is withdrawn, then deposited (both if needed):
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L440-L465

Then the position is reduced and increased (both if needed)
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L499-L519

The problem is that rebalancing can revert which leaves the user that wants to execute an operation in the Vault no other choice other than sending additional assets to the Vault (note that calling the `deposit` function might not be possible because rebalancing reverts). The user needs to send the funds directly to the Vault, without calling the deposit function. Thereby this would be a loss of funds for the user because the additional funds would be shared across all users.

## Vulnerability Detail
Assume e.g. that the amount of collateral that the Vault has deposited into a Product is a little bit over the minimum collateral amount.

When the Product's makers are settled at a loss, the rebalancing logic in the Vault then tries to withdraw all collateral from the Product because it is below the minimum amount.

However this causes a revert because the position has not been closed yet and zero collateral cannot maintain the position.

## Impact
The Vault can get stuck and to resolve the situation, assets need to be sent to the Vault which are then essentially lost because they are shared among all users.

## Code Snippet
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L431-L434

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L440-L465

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L499-L519

## Tool used
Manual Review

## Recommendation
It should not be possible that the rebalancing fails because it is required for all actions that can be executed in the Vault.
However solving the issue is not as simple as changing the order of actions in the call to `_rebalance` to this:
1. reduce position
2. reduce collateral
3. increase collateral
4. increase position

That's because there is delayed settlement in the Product and a change in position size is not immediately reflected.
Therefore a solution needs to be adopted that first reduces the position and then waits for settlement until steps 2-4 are executed.

**Comment by SergeKireev** [comment]
Escalate for 10 USDC

The issue is valid but should be of medium severity since it essentially causes a griefing.

Indeed any user can unblock the situation by simply depositing into the BalancedVault:

-  Assets are pulled from the user:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L172

- When `targetCollateral` is evaluated:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L442

_assets() includes the amount just deposited in, and is above `controller.minCollateral()`. Since the correct amount of shares is minted to the depositor, the depositor does not loses funds as described in this report.

**Comment by KenzoAgada** [comment]
I agree with the escalation. Severity should be changed to medium.

**Comment by jacksanford1** [comment]
Would argue this is a Low because it's just a freezing of funds and the solution to get funds unstuck doesn't seem too difficult. 

Especially if @SergeKireev is correct about this:
> Since the correct amount of shares is minted to the depositor, the depositor does not loses funds as described in this report.

@KenzoAgada @SergeKireev @roguereddwarf

**Comment by roguereddwarf** [comment]
There is still the case when there is pro-rate claiming going on.
https://github.com/sherlock-audit/2023-05-perennial/blob/0f73469508a4cd3d90b382eac2112f012a5a9852/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L223

When the user that wants to resolve the freezing deposits in this situation, he DOES lose funds (he does get the shares, but they won't be worth anything).

At the time of making the deposit, the user cannot be sure of whether there will be pro-rate claiming or not.

So there is still the possibility of losing funds.

Additionally, I don't think we should take the current value for MIN_COLLATERAL=10USD literally.
It could also go to 100 USD or 1 USD.

In summary, there can be a case made for a loss of funds which is more than a tiny value.

**Comment by jacksanford1** [comment]
@SergeKireev Do you agree that there is a case where the depositor loses their funds (isn't awarded pro-rata shares)?

**Comment by eliteWalrus4164** [comment]
@jacksanford1
The prorating measure makes it a moot point.

If the user Bob is trying to deposit when prorated claiming is in-progress, ie this condition is verified:
https://github.com/sherlock-audit/2023-05-perennial-SergeKireev/blob/c90b017ad432b283bcfbec594f80e18204ee98c3/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L223

He indeed risks losing part of his deposit. This is a temporary situation, and Bob could wait until claims are processed to try to deposit.

Please note that this loss can happen regardless of the vault being in the situation described in the initial report.
Thus I would argue that this loss should not affect the judgement on the report, which has no mention of it, and be considered as an entirely different bug discovered due to the discussion on this report.

**Comment by KenzoAgada** [comment]
The simple problematic scenario that I envisioned is this:
Let's say a user wanted to withdraw his funds and now the vault is stuck and reverting. What is he to do? He just wanted to exit. He probably wouldn't even initially know what's the problem. Even after asking in Discord and waiting for answer and understanding, why (fundamentally) should he need to deposit more? What if he doesn't have funds available? What if nobody else deposits? I don't think it's fair to expect a user to deposit more funds when he just wanted to exit.

I do concede 3 points:
- the original submission incorrectly stated that deposit will revert / user will lose donated assets
- practically it is possible to fix the jamming by sending more assets to the vault
- there is probably no easy viable fix for this codewise

But I don't think these are enough to consider the issue as low.

**Comment by jacksanford1** [comment]
To me this scenario is already a bit of an edge case, and the fix for it seems very reasonable (adding more funds to the vault). Is there a minimum amount of funds require to make the vault unstuck? If it can be a very small value ($1), then I see this as a Low. If it's a very large value (potentially a large % of the assets in the vault) then I could see it being riskier to perform the necessary operation to "unstick" the vault. 

Still considering this Low but will wait to hear about the amount of funds necessary to unstick the vault from @roguereddwarf or @KenzoAgada

**Comment by roguereddwarf** [comment]
As pointed out earlier there is a maximum: 

> (Additionally, in the inefficient solution of just donating to the vault as suggested by the report, the absolute maximum which can be lost is MIN_COLLATERAL=10 USD as per values in current deployments)

I don't think we can assume that for all Vaults this will always be 10 USD.
100 USD or even 1000 USD seems reasonable.
E.g. a case can be if Gas costs are very high on Ethereum we might require higher minimum deposits.

I don't think we can reasonably assume this will always be <=10 USD

**Comment by KenzoAgada** [comment]
The `minCollateral` is 10USD on Arbitrum and 100USD on Ethereum.
(Though at the moment Vaults are not deployed on Ethereum.)

**Comment by jacksanford1** [comment]
@roguereddwarf @KenzoAgada Agree that we can't assume it will always be 10 USD. But it is `minCollateral` so it seems safe to assume that it will always be a relatively small value. Even if it were 1000 (2 orders of magnitude more than Arbitrum value) this issue would not be considered material enough for Sherlock. It's definitely an inconvenience and seems to be a valid Low issue, but that amount of funds at risk is not material enough to constitute a Medium. Still going with Low on this one.

**Comment by jacksanford1** [comment]
Result:
Low
Has duplicates
See previous message for reasoning.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/66/#issuecomment-1613491514): accepted
