### ISSUE TITLE
cergyk - Epoch can be complete when short oracle version is lagging

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#84]
cergyk

medium

# Epoch can be complete when short oracle version is lagging

## Summary
An epoch can be deemed complete by a balanced vault, even if a short oracle has an earlier version

## Vulnerability Detail
To check if an epoch is completed, we need to check that both short and long oracles have advanced to the next version. If both start on the same version current check works fine:

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L343-L351

But as we can see, current epoch is only set from long version:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L393

So if the short version is currently one version behind, since it is != from current version, the epoch can be marked as completed by the vault

Example:
Current epoch version = N

Balanced vault is comprised of two markets: 

Market 1:
    current short version = N-1
    current long version  = N+1

Market 2:
    current short version = N+1
    current long version  = N+1

currentEpochComplete = true.

If the lagging short version increases later, it will still allow for subsequent epoch updates, since it remains different (albeit lower than) current epoch version.

## Impact
The accounting of the vault is flawed, and may not rebalance correctly

## Tool used
Manual Review

## Recommendation
use `>=` comparator instead of `==`;

**Comment by SergeKireev** [comment]
Escalate for 10 USDC

Here's a simpler example:

During a vault initialization all of the versions for current epoch are initialized to the long latestversion:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L393
Not any short version is checked during this process.

If during initialization any short oracle is one version behind and stalling, subsequently if all other oracles operate normal, and advance to the next version, the epoch will be considered complete because:

At initialization short oracle for market `i` is one version behind, and the version of the epoch for market `i` is set to be the one of the long oracle. Since all other oracles operate normally and advance of one version, all oracles are once again in a `different` version than the one of their epoch.

And so the epoch completes successfully even though a short oracle is indefinitely lagging
